name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t emnabelguith/project-92a0051e-cca5-4e5c-8355-29d8ddcf9d73:latest .
        docker push emnabelguith/project-92a0051e-cca5-4e5c-8355-29d8ddcf9d73:latest

  deploy-and-health-check:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: Pull Docker image
      run: docker pull emnabelguith/project-92a0051e-cca5-4e5c-8355-29d8ddcf9d73:latest

    - name: Run Docker container (Web App)
      run: docker run -d --name my-app -p 8000:8000 emnabelguith/project-92a0051e-cca5-4e5c-8355-29d8ddcf9d73:latest
    
    - name: Health Check (Web App)
      run: |
        set -x
        for i in {1..30}; do
          if curl -f http://localhost:8000/; then
            echo "Health check successful!"
            exit 0
          fi
          echo "Health check failed, retrying in 2 seconds..."
          sleep 2
        done
        echo "Health check failed after multiple retries."
        docker logs my-app
        exit 1

    - name: Clean up Docker container (Web App)
      if: always()
      run: docker stop my-app && docker rm my-app || true
